<#
.SYNOPSIS
    Wire every installed emulator and ROM folder into ES-DE.

.DESCRIPTION
    Windows counterpart of the Linux configure_esde role and
    macos/bootstrap.sh. Writes two files into <EsdeHome>\custom_systems\:

      es_find_rules.xml  one staticpath rule per installed emulator, pointing
                         at the real exe (ES-DE merges it with its bundled
                         rules, so nothing depends on PATH, junctions or where
                         winget happened to put a package)
      es_systems.xml     every system from config/esde-systems.psd1 with its
                         ROM folder and default emulator; it overrides only
                         those systems in ES-DE's bundled list

    Also reports (or, with CreateRomDirs, creates) the per-system ROM folders.
    Existing files are backed up as <file>.bak.<timestamp> before a change.
    Never installs anything -- run install-apps.ps1 first.

.PARAMETER Action
    'Check' (default) previews without writing. 'Configure' writes.

.EXAMPLE
    ./bootstrap.ps1 -Action Check
    ./bootstrap.ps1 -Action Configure
#>
[CmdletBinding()]
param(
    [ValidateSet('Check', 'Configure')]
    [string]$Action = 'Check',

    [string]$ConfigPath,

    [Nullable[bool]]$CreateRomDirs = $null
)

$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $scriptRoot 'lib\common.ps1')
. (Join-Path $scriptRoot 'lib\gamelists.ps1')

$apply = $Action -eq 'Configure'
$config = Get-DgConfig -ConfigPath $ConfigPath -ScriptRoot $scriptRoot
if ($null -ne $CreateRomDirs) { $config.CreateRomDirs = $CreateRomDirs }

$apps = @(Get-DgApps -ScriptRoot $scriptRoot)
$esdeData = Import-PowerShellDataFile -Path (Join-Path $scriptRoot 'config\esde-systems.psd1')
$systems = $esdeData.Systems
$customDir = Join-Path $config.EsdeHome 'custom_systems'
Write-Host "ES-DE home: $($config.EsdeHome)$(if ($config.EsdeHomeSource) { " ($($config.EsdeHomeSource))" })" -ForegroundColor Cyan

function ConvertTo-XmlText { param([string]$Text) [Security.SecurityElement]::Escape($Text) }

function Write-GeneratedFile {
    param([string]$Path, [string]$Content, [string]$Label)
    [void][xml]$Content
    $current = if ([IO.File]::Exists($Path)) { [IO.File]::ReadAllText($Path) } else { $null }
    if ($current -eq $Content) {
        Write-Host "[$Label] $Path is up to date" -ForegroundColor Green
        return
    }
    if (-not $apply) {
        Write-Host "[$Label] $Path would be $(if ($current) { 'updated' } else { 'created' })" -ForegroundColor Yellow
        return
    }
    [void][IO.Directory]::CreateDirectory((Split-Path -Parent $Path))
    if ($null -ne $current) {
        [IO.File]::Copy($Path, "$Path.bak.$(Get-Date -Format 'yyyyMMddHHmmss')", $true)
    }
    [IO.File]::WriteAllText($Path, $Content, (New-Object Text.UTF8Encoding $false))
    Write-Host "[$Label] $Path $(if ($current) { 'updated (previous version backed up)' } else { 'created' })" -ForegroundColor Yellow
}

# ---------------------------------------------------------------------------
# Emulators
# ---------------------------------------------------------------------------

Write-Host "`n== Emulators (root: $($config.EmulatorsRoot)) ==" -ForegroundColor Cyan

$rows = foreach ($app in $apps) {
    [PSCustomObject]@{
        Name    = $app.name
        Systems = ($app.systems -join ' ')
        Path    = Resolve-AppRealExePath -App $app -EmulatorsRoot $config.EmulatorsRoot
        App     = $app
    }
}
$rows | Select-Object Name, @{ n = 'Installed'; e = { [bool]$_.Path } }, Path | Format-Table -AutoSize

$missing = @($rows | Where-Object { -not $_.Path })
if ($missing) {
    Write-Host "Not installed: $($missing.Name -join ', ') -- their systems stay listed in ES-DE but won't launch until installed (./install-apps.ps1)." -ForegroundColor Yellow
}

# ---------------------------------------------------------------------------
# es_find_rules.xml
# ---------------------------------------------------------------------------

Write-Host "`n== ES-DE configuration ($customDir) ==" -ForegroundColor Cyan

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0"?>')
[void]$sb.AppendLine('<!-- Generated by distrobox-gaming windows/bootstrap.ps1. Manual edits are overwritten (a backup is kept). -->')
[void]$sb.AppendLine('<ruleList>')
foreach ($row in $rows | Where-Object { $_.Path }) {
    foreach ($emuName in $row.App.emulatorNames) {
        [void]$sb.AppendLine("    <emulator name=""$(ConvertTo-XmlText $emuName)"">")
        [void]$sb.AppendLine('        <rule type="staticpath">')
        [void]$sb.AppendLine("            <entry>$(ConvertTo-XmlText $row.Path)</entry>")
        [void]$sb.AppendLine('        </rule>')
        [void]$sb.AppendLine('    </emulator>')
    }
}
[void]$sb.AppendLine('</ruleList>')
Write-GeneratedFile -Path (Join-Path $customDir 'es_find_rules.xml') -Content $sb.ToString() -Label 'find rules'

# ---------------------------------------------------------------------------
# es_systems.xml
# ---------------------------------------------------------------------------

function Get-RomPath {
    param([string]$System)
    if ($config.RomPaths -and $config.RomPaths.ContainsKey($System)) { return $config.RomPaths[$System] }
    return Join-Path $config.RomRoot $System
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0"?>')
[void]$sb.AppendLine('<!-- Generated by distrobox-gaming windows/bootstrap.ps1 from config/esde-systems.psd1. Manual edits are overwritten (a backup is kept). -->')
[void]$sb.AppendLine('<systemList>')
foreach ($s in $systems) {
    [void]$sb.AppendLine('    <system>')
    [void]$sb.AppendLine("        <name>$(ConvertTo-XmlText $s.Name)</name>")
    [void]$sb.AppendLine("        <fullname>$(ConvertTo-XmlText $s.FullName)</fullname>")
    [void]$sb.AppendLine("        <path>$(ConvertTo-XmlText (Get-RomPath -System $s.Name))</path>")
    [void]$sb.AppendLine("        <extension>$(ConvertTo-XmlText $s.Extension)</extension>")
    foreach ($c in $s.Commands) {
        [void]$sb.AppendLine("        <command label=""$(ConvertTo-XmlText $c.Label)"">$(ConvertTo-XmlText $c.Cmd)</command>")
    }
    [void]$sb.AppendLine("        <platform>$(ConvertTo-XmlText $s.Platform)</platform>")
    [void]$sb.AppendLine("        <theme>$(ConvertTo-XmlText $s.Theme)</theme>")
    [void]$sb.AppendLine('    </system>')
}
[void]$sb.AppendLine('</systemList>')
Write-GeneratedFile -Path (Join-Path $customDir 'es_systems.xml') -Content $sb.ToString() -Label 'systems'

# ---------------------------------------------------------------------------
# Gamelists, scraped media and ES-DE settings (configure_esde counterparts)
# ---------------------------------------------------------------------------

Write-Host "`n== Gamelists and media ==" -ForegroundColor Cyan
$gamelistDir = Join-Path $config.EsdeHome 'gamelists'
$verb = if ($apply) { 'written' } else { 'would be written' }

$ps4 = Update-Ps4Gamelist -RomDir (Get-RomPath -System 'ps4') -OutFile (Join-Path $gamelistDir 'ps4\gamelist.xml') -Apply $apply
if ($null -eq $ps4) { Write-Host '[ps4] no CUSA folders with eboot.bin yet' -ForegroundColor DarkGray }
else { Write-Host "[ps4] gamelist with $($ps4.Games) game(s) from PARAM.SFO $(if ($ps4.Changed) { $verb } else { 'up to date' })" -ForegroundColor $(if ($ps4.Changed) { 'Yellow' } else { 'Green' }) }

foreach ($sys in $esdeData.ArcadeCloneSystems) {
    $r = Update-ArcadeCloneGamelist -SourceFile (Join-Path (Get-RomPath -System $sys) 'gamelist.xml') `
        -OutFile (Join-Path $gamelistDir "$sys\gamelist.xml") -Apply $apply
    if ($null -eq $r) { Write-Host "[$sys] no Skraper gamelist.xml in the ROM folder" -ForegroundColor DarkGray }
    else { Write-Host "[$sys] $($r.Games) game(s), $($r.Hidden) clone(s) hidden, $(if ($r.Changed) { $verb } else { 'up to date' })" -ForegroundColor $(if ($r.Changed) { 'Yellow' } else { 'Green' }) }
}

$romDirs = @{}
foreach ($s in $systems) {
    $d = Get-RomPath -System $s.Name
    if ([IO.Directory]::Exists($d)) { $romDirs[$s.Name] = $d }
}
$media = Sync-EsdeMedia -SystemRomDirs $romDirs -MediaDir (Join-Path $config.EsdeHome 'downloaded_media') -Apply $apply
Write-Host "[media] $media scraped image(s) $(if ($apply) { 'linked into' } else { 'to link into' }) downloaded_media"

$esdeSettings = Set-EsdeSettings -SettingsFile (Join-Path $config.EsdeHome 'settings\es_settings.xml') -Apply $apply -Settings @(
    @{ Type = 'string'; Name = 'ROMDirectory'; Value = $config.RomRoot }
    @{ Type = 'bool'; Name = 'ParseGamelistOnly'; Value = ([bool]$config.ParseGamelistOnly).ToString().ToLower() }
)
if ($null -eq $esdeSettings) { Write-Host '[settings] es_settings.xml not created yet -- start ES-DE once, then rerun' -ForegroundColor DarkGray }
else { Write-Host "[settings] ROMDirectory and ParseGamelistOnly $(if ($esdeSettings) { if ($apply) { 'updated' } else { 'would be updated' } } else { 'up to date' })" -ForegroundColor $(if ($esdeSettings) { 'Yellow' } else { 'Green' }) }

# ---------------------------------------------------------------------------
# ROM directories
# ---------------------------------------------------------------------------

Write-Host "`n== ROM directories (root: $($config.RomRoot)) ==" -ForegroundColor Cyan

$romRows = foreach ($s in $systems) {
    $path = Get-RomPath -System $s.Name
    $exists = [IO.Directory]::Exists($path)
    $created = $false
    if (-not $exists -and $apply -and $config.CreateRomDirs) {
        [void][IO.Directory]::CreateDirectory($path)
        $exists = $true
        $created = $true
    }
    [PSCustomObject]@{ System = $s.Name; Path = $path; Exists = $exists; Created = $created }
}

$missingRoms = @($romRows | Where-Object { -not $_.Exists })
$createdRoms = @($romRows | Where-Object { $_.Created })
Write-Host "$($romRows.Count - $missingRoms.Count) of $($romRows.Count) system folders exist$(if ($createdRoms) { " ($($createdRoms.Count) created)" })."
if ($missingRoms) {
    Write-Host "Missing: $($missingRoms.System -join ', ')" -ForegroundColor Yellow
    if (-not $config.CreateRomDirs) {
        Write-Host "Missing folders are only reported. Set CreateRomDirs = `$true in config\localhost.psd1 (or pass -CreateRomDirs `$true) to create them." -ForegroundColor Yellow
    }
}

if ($apply) {
    Write-Host "`nConfigure complete. Restart ES-DE to pick up the changes." -ForegroundColor Green
} else {
    Write-Host "`nCheck complete. Nothing was written. Run with -Action Configure to apply." -ForegroundColor Green
}
